//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.17 at 09:53:43 AM CEST 
//


package com.tieto.services.weather.response.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tieto.services.weather.response.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tieto.services.weather.response.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWeatherRequest }
     * 
     */
    public GetWeatherRequest createGetWeatherRequest() {
        return new GetWeatherRequest();
    }

    /**
     * Create an instance of {@link GetWeatherResponse }
     * 
     */
    public GetWeatherResponse createGetWeatherResponse() {
        return new GetWeatherResponse();
    }

    /**
     * Create an instance of {@link WeatherDTO }
     * 
     */
    public WeatherDTO createWeatherDTO() {
        return new WeatherDTO();
    }

    /**
     * Create an instance of {@link ErrorDTO }
     * 
     */
    public ErrorDTO createErrorDTO() {
        return new ErrorDTO();
    }

}
